---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname renovate-operator
  namespace: &namespace renovate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *appname
      namespace: *namespace
  interval: 1h
  path: "./kubernetes/apps/renovate/renovate-operator/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-jobs
  namespace: &namespace renovate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  dependsOn:
    - name: renovate-operator
  interval: 1h
  path: "./kubernetes/apps/renovate/renovate-operator/jobs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
