---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: renovate-operator
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Automated dependency updates
    gethomepage.dev/group: Development
    gethomepage.dev/icon: sh-mend-renovate.svg
    gethomepage.dev/name: Renovate
    gethomepage.dev/app: renovate
spec:
  hostnames:
    - renovate.hemma.dev
  parentRefs:
    - name: internal
      namespace: networking
  rules:
    - backendRefs:
        - name: renovate-operator
          namespace: renovate
          port: 8081
