apiVersion: v1
kind: Secret
metadata:
    name: minio
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:WgRl80w=,iv:m2ziI4GOz4iEJuL9iIa+JJ7MjqqmNTrZwbLdJnHiR+c=,tag:AfGCP4Air6jLx3z68TDwAA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:qyE/ZkcYUiyRoQZp,iv:Nkwxum2sjFfbVsnoDMFxq4BiKK3djlm6kG/fTjVcykM=,tag:+wEvkSzuOgRjap9y7KLPcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fq0xqmcc0shymjj2whvgscmhydmzmrahdfny27pku8mx2erqzf6slsv3dg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaldKazREODZSRFZrMFFO
            OXYrWEx4N1h1RkZYMExRSUZoaGVrSEIyaW44CkFJV0hxcGZtTUhwNkdERStjd21X
            UUJlYU5HL3hhK3FqcityU3hra2hNOFkKLS0tIGJUYlhjdFRIWlAxakhUeGhqM040
            bHpmSjVtZ3NwL2ZUd1dvK3pTVXROSHcKGREG+ItohQGgTuXoaoG0Rxebx0Yl7Qp7
            XitkLdDjiD2D3uDak93S8+WFEBFRnfkl8RWASP4u8lsO2zTxG4ezlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T13:34:12Z"
    mac: ENC[AES256_GCM,data:K2Ee+A9Vr72SGa2r5ceJUgrFOognibKaIzEJ2rQGKS+yQ6HAixreCNAhOfKczo4WTr5uqUjEnReIRyWHJwIKAwFx5RiCkYogPHo60mVG163ArBOc5L67/O70aXGh/HNtW8HC+u1vGSFyF1GGBZ5PE6x/dsocw2CYq3UL95UtFmg=,iv:Qfs2fxpK7fo+2KSvrDKv4s7F1RfIKOfEr74V/GuR4r0=,tag:kRX0qcRRMXuB1Nfnt+K6lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-prometheus
stringData:
    token: ENC[AES256_GCM,data:GqkY/PcP9HLQt9jomTEmRIXUsTMpL/ToJnpo2OlOMRLPJFqKXIAbi0jsovWslfzO+Npx2lB7mRNTgWQNHackMf6W1RmilLU551MsuAtvhugLtVhF86rwwntqcSTzBS0xE+7wwWRe8M4ksUU1IJKPLZMEBFYiva8Y/hNL7lFI3oH9AWJTFnkg/jAoO5ylKNTy1+8cpM3OSSeZWQVY7PcuJwtZrnMu3pUDkdFeSSIF0kcWdXgb539LYt67vf6BPjbyPhJvmqaTsT9m627MKfTyPQVvOlmjxet3c3g=,iv:G8aKtYbO8e5fT+sk+XB4a8QjR/vtPbe9wPlIkP8tegA=,tag:8klRKA86OW9JqTcE5exupw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fq0xqmcc0shymjj2whvgscmhydmzmrahdfny27pku8mx2erqzf6slsv3dg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaldKazREODZSRFZrMFFO
            OXYrWEx4N1h1RkZYMExRSUZoaGVrSEIyaW44CkFJV0hxcGZtTUhwNkdERStjd21X
            UUJlYU5HL3hhK3FqcityU3hra2hNOFkKLS0tIGJUYlhjdFRIWlAxakhUeGhqM040
            bHpmSjVtZ3NwL2ZUd1dvK3pTVXROSHcKGREG+ItohQGgTuXoaoG0Rxebx0Yl7Qp7
            XitkLdDjiD2D3uDak93S8+WFEBFRnfkl8RWASP4u8lsO2zTxG4ezlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T13:34:12Z"
    mac: ENC[AES256_GCM,data:K2Ee+A9Vr72SGa2r5ceJUgrFOognibKaIzEJ2rQGKS+yQ6HAixreCNAhOfKczo4WTr5uqUjEnReIRyWHJwIKAwFx5RiCkYogPHo60mVG163ArBOc5L67/O70aXGh/HNtW8HC+u1vGSFyF1GGBZ5PE6x/dsocw2CYq3UL95UtFmg=,iv:Qfs2fxpK7fo+2KSvrDKv4s7F1RfIKOfEr74V/GuR4r0=,tag:kRX0qcRRMXuB1Nfnt+K6lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
