---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ext-postgres-operator-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://movetokube.github.io/postgres-operator/
  timeout: 3m
