---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: haproxy-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://haproxytech.github.io/helm-charts
  timeout: 5m
