---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gramps
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gramps-secret
    creationPolicy: Owner
  data:
    - secretKey: GRAMPSWEB_SECRET_KEY
      remoteRef:
        key: gramps
        property: GRAMPSWEB_SECRET_KEY
