---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname actions-runner-controller
  namespace: &namespace dev
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: onepassword-store
      namespace: security
  interval: 30m
  path: "./kubernetes/apps/dev/actions-runner-controller/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname-runner actions-runner-controller-runners
  namespace: &namespace dev
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname-runner
  dependsOn:
    - name: actions-runner-controller
      namespace: dev
  interval: 30m
  path: "./kubernetes/apps/dev/actions-runner-controller/runners"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
