---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sops.secrets.yaml
  - ./postgres-cluster.yaml
  - ./scheduled-backup.yaml
  - ./loadbalancer.yaml
  - ./gatus.yaml
