---
apiVersion: v1
kind: Service
metadata:
  name: postgres16-loadbalancer
  labels:
    postgresql: postgres16
    role: primary
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${LB_POSTGRES}
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    postgresql: postgres16
    role: primary
  type: LoadBalancer
