---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-jellyfin-config
spec:
  schedule: "0 9 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          # Stagger jobs to run randomly within X seconds to avoid backing up all apps at once
          initContainers:
            - name: sleep
              image: ghcr.io/ahinko/simple-k8s-backup:v4.2.74
              command: ["/sleep.sh"]
              args: ["1", "300"]
          containers:
            - name: backup-jellyfin
              image: ghcr.io/ahinko/simple-k8s-backup:v4.2.74
              args:
                - /run.sh
              envFrom:
                - secretRef:
                    name: backups-secrets
              env:
                - name: BACKUP_NAME
                  value: &appname jellyfin
                - name: DELETE_OLDER_THAN
                  value: "14d"
                - name: EXCLUDE
                  value: "./metadata"
                - name: HEALTHCHECK_URL
                  value: "http://uptime-kuma.monitoring:3001/api/push/DaWtMnBk5h?status=up&msg=OK&ping="
              volumeMounts:
                - name: backup-persistent-storage
                  mountPath: /jellyfin
          restartPolicy: Never
          volumes:
            - name: backup-persistent-storage
              persistentVolumeClaim:
                claimName: jellyfin-config
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - *appname
                  topologyKey: kubernetes.io/hostname
