---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeops-bot-pem
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homeops-bot-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: github-homeops-bot
        property: homeops_bot_app_key
