---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Monitoring and observability platform
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: sh-headlamp.svg
    gethomepage.dev/name: Headlamp
    gethomepage.dev/app: headlamp
spec:
  hostnames:
    - headlamp.hemma.dev
  parentRefs:
    - name: internal
      namespace: networking
  rules:
    - backendRefs:
        - name: headlamp
          namespace: observability
          port: 4466
