---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubernetes-sigs-node-feature-discovery-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  timeout: 3m
