---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/giantswarm/silence-operator/v0.11.2/config/crd/monitoring.giantswarm.io_silences.yaml
  - ./helm-release.yaml
  - ./rbac.yaml
