---
version: "3.8"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.40.0.7998-c29d4c0c8
    restart: always
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Stockholm
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://192.168.20.2:32400/
    hostname: Atlas
    volumes:
      - /tank/plex/database:/config
      - /pool/media:/data
      - /tank/shares/ahinko/Bilder:/bilder
    devices:
      - /dev/dri:/dev/dri
