---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./openebs/install.yaml
  - ./snapshot-controller/install.yaml
  - ./spegel/install.yaml
  - ./volsync/install.yaml
