---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-bootstrap"
spec:
  restic:
    accessModes:
      - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
    capacity: "${VOLSYNC_CAPACITY:-1Gi}"
    cleanupCachePVC: true
    cleanupTempPVC: true
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    enableFileDeletion: true
    moverSecurityContext:
      runAsUser: ${APP_UID:-2000}
      runAsGroup: ${APP_GID:-2000}
      fsGroup: ${APP_GID:-2000}
    repository: "${APP}-volsync-restic"
    storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
  trigger:
    manual: restore-once
