---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  METALLB_ARP_RANGE: "192.168.20.200-192.168.20.255"

  CLUSTER_NAME: "metal"

  NFS_SERVER_ADDR: "192.168.20.2"

  # Load balancers
  LB_HASS: "192.168.20.201"
  LB_EMQX: "192.168.20.203"
  LB_POSTGRES: "192.168.20.204"
  LB_INGRESS: "192.168.20.205"
  LB_MINECRAFT: "192.168.20.206"
  LB_SLSKD: "192.168.20.207"
  LB_K8S_GATEWAY_HOMELAB: "192.168.20.208"
  LB_JELLYFIN: "192.168.20.209"
  LB_K8S_GATEWAY_SOCIAL: "192.168.20.210"
