---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.2-202602201511-standard-trixie
  storage:
    size: 100Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres18-local-ceph
        serverName: postgres18-v2
  postgresql:
    extensions:
      - name: postgis
        image:
          # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgis-extension
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.1-18-trixie
        ld_library_path:
          - system
      - name: vchord
        image:
          # renovate: datasource=docker depName=ghcr.io/tensorchord/vchord-scratch
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.0.0
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
    parameters:
      max_connections: "100"
      shared_buffers: 128MB
    shared_preload_libraries:
      - vchord.so

  bootstrap:
    initdb: {}

  #   recovery:
  #     source: origin

  # externalClusters:
  #   - name: origin
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: postgres18-local-ceph # same as in old cluster
  #         serverName: postgres18-v2 # same as in old cluster
