---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./cronjob.yaml
  - ./external-secret.yaml
  - ./loadbalancer.yaml
  - ./objectbucket-claim.yaml
  - ./objectstore.yaml
  - ./pod-monitor.yaml
  - ./prometheus-rule.yaml
  - ./scheduled-backup.yaml
